### PR TITLE
README Refactor

### PR DESCRIPTION
**Pull request by ElectronicsArchiver**
[Badge Suggestions]: https://img.shields.io/badge/Ｒｅｐｏｓｉｔｏｒｙ_Ｓｕｇｇｅｓｔｉｏｎｓ-609926?style=for-the-badge&logoColor=white&logo=GitHub
[Badge Changes]: https://img.shields.io/badge/Ｃｈａｎｇｅｓ-D81939?style=for-the-badge&logoColor=white&logo=GitLFS
[Badge Ask]: https://img.shields.io/badge/Ｐｌｅａｓｅ_Ａｓｋ_Ｍｅ-73398D?style=for-the-badge&logoColor=white&logo=AskUbuntu

[Widgets]: https://github.com/MarkedDown/Disable/blob/main/Features/Widgets.md
[Tabs]: https://github.com/MarkedDown/Disable/blob/main/Features/Tabs.md

<br>
<br>

<div align = center>

[<kbd> <br> Please Check The **Preview** <br> </kbd>][Preview]

</div>
  
<br>
<br>

## ![Badge Suggestions]

  <br>

- **Add Tags**

  <br>

- ***[Disable Unused Widgets][Widgets]***:

  - `Packages`

  - `Releases`

  <br>

- ***[Disable Unused Tabs][Tabs]***:

  - `Projects`

  - `Actions`

  - `Wiki`

<br>
<br>

## ![Badge Changes]

- Sorted root folders

- General formatting / spacing

- Added license / status badges

- Added quicklinks

#### Note

Due to the reodering of files git seems to have 
retroactively applied your hardware folders 
gitignore and removed the temporary `.bak` 
file, so no harm done.

<br>
<br>

## ![Badge Ask]

- ***If you have any questions.***

- ***In case you do not agree with some of the changes made in this PR***, <br>
  *please first let me know about them, before disregarding it entirely so*<br>
  *we can possibly find a middle ground and have it not go to waste.*

<br>
<br>

[Preview]: https://github.com/ElectronicsArchiver/scuznet

### CODE REVIEW

**Comment by saybur** [comment]
There are some good ideas here, but overall these changes seem stylistic in nature and clash with how I personally like things to be laid out. I am also not a fan of external dependencies to images. The things I'd be open to accepting:

- Some of the README cleanups.
- Adding the .gitignore
- Moving source to its own folder (this is a holdover from earlier in the project)

**Comment by ElectronicsArchiver** [comment]
Well I can download the generated badges and
put them into a `Resources` folder if you'd like~

**Comment by ElectronicsArchiver** [comment]
@saybur Could you please follow up with this..

**Comment by saybur** [comment]
Sorry for the delay, I've been occupied with offline life stuff.

I appreciate you going to the work of submitting this, but I'm going to close this contribution without accepting it. The majority of the changes are focused on a style that clashes with the spartan / low-graphics layout I prefer. For reorganization, I will be resolving that myself later once the majority of the work on the development branch is complete and gets merged with the main branch.

If you would like to contribute a `.gitignore` or cleaned up `README.md` without graphics, please feel free to do so in a separate PR.

**Pull request closed without merging**
